// Declare all typefbrg
// The value should not changed as it is stored in the database
// The variable name can however be changed
export const ACTIVITY_TYPE_ELECTRICITY = 'ACTIVITY_TYPE_ELECTRICITY';
export const ACTIVITY_TYPE_ELECTRIC_VEHICLE_CHARGING = 'ACTIVITY_TYPE_ELECTRIC_VEHICLE_CHARGING';
export const ACTIVITY_TYPE_TRANSPORTATION = 'ACTIVITY_TYPE_TRANSPORTATION';
export const ACTIVITY_TYPE_MEAL = 'ACTIVITY_TYPE_MEAL';
export const ACTIVITY_TYPE_PURCHASE = 'ACTIVITY_TYPE_PURCHASE';

/* Transportation */
export const TRANSPORTATION_MODE_PLANE = 'plane';
export const TRANSPORTATION_MODE_BIKE = 'bike';
export const TRANSPORTATION_MODE_CAR = 'car';
export const TRANSPORTATION_MODE_BUS = 'bus';
export const TRANSPORTATION_MODE_PUBLIC_TRANSPORT = 'public_transport';
export const TRANSPORTATION_MODE_TRAIN = 'train';
export const TRANSPORTATION_MODE_FERRY = 'ferry';
export const TRANSPORTATION_MODE_ESCOOTER = 'escooter';

/* Meals */
export const MEAL_TYPE_VEGAN = 'MEAL_TYPE_VEGAN';
export const MEAL_TYPE_VEGETARIAN = 'MEAL_TYPE_VEGETARIAN';
export const MEAL_TYPE_MEAT_OR_FISH = 'MEAL_TYPE_MEAT_OR_FISH';

/* Purchases */
// Food and beverages
export const PURCHASE_CATEGORY_FOOD_SUPERMARKET = 'PURCHASE_CATEGORY_FOOD_SUPERMARKET';
export const PURCHASE_CATEGORY_FOOD_BAKERY = 'PURCHASE_CATEGORY_FOOD_BAKERY';

// Stores
export const PURCHASE_CATEGORY_STORE_DEPARTMENT = 'PURCHASE_CATEGORY_STORE_DEPARTMENT';
export const PURCHASE_CATEGORY_STORE_CLOTHING = 'PURCHASE_CATEGORY_STORE_CLOTHING';
export const PURCHASE_CATEGORY_STORE_HARDWARE = 'PURCHASE_CATEGORY_STORE_HARDWARE';
export const PURCHASE_CATEGORY_STORE_PET = 'PURCHASE_CATEGORY_STORE_PET';
export const PURCHASE_CATEGORY_STORE_ELECTRONIC = 'PURCHASE_CATEGORY_STORE_ELECTRONIC';
export const PURCHASE_CATEGORY_STORE_BOOKS = 'PURCHASE_CATEGORY_STORE_BOOKS';
export const PURCHASE_CATEGORY_STORE_GARDEN = 'PURCHASE_CATEGORY_STORE_GARDEN';
export const PURCHASE_CATEGORY_STORE_FLORIST = 'PURCHASE_CATEGORY_STORE_FLORIST';
export const PURCHASE_CATEGORY_STORE_BARBER_BEAUTY = 'PURCHASE_CATEGORY_STORE_BARBER_BEAUTY';
export const PURCHASE_CATEGORY_STORE_HOUSE_FURNISHING = 'PURCHASE_CATEGORY_STORE_HOUSE_FURNISHING';
export const PURCHASE_CATEGORY_STORE_EQUIPMENT_FURNITURE = 'PURCHASE_CATEGORY_STORE_EQUIPMENT_FURNITURE';
export const PURCHASE_CATEGORY_STORE_HOUSEHOLD_APPLIANCE = 'PURCHASE_CATEGORY_STORE_HOUSEHOLD_APPLIANCE';

// Healthcare
export const PURCHASE_CATEGORY_HEALTHCARE_PHARMARCY = 'PURCHASE_CATEGORY_HEALTHCARE_PHARMARCY';
export const PURCHASE_CATEGORY_HEALTHCARE_DOCTOR = 'PURCHASE_CATEGORY_HEALTHCARE_DOCTOR';

// Transportation
export const PURCHASE_CATEGORY_TRANSPORTATION_FUEL = 'PURCHASE_CATEGORY_TRANSPORTATION_FUEL';
export const PURCHASE_CATEGORY_TRANSPORTATION_AUTOMOTIVE_PARKING = 'PURCHASE_CATEGORY_TRANSPORTATION_AUTOMOTIVE_PARKING';
export const PURCHASE_CATEGORY_TRANSPORTATION_AUTOMOTIVE_PARTS = 'PURCHASE_CATEGORY_TRANSPORTATION_AUTOMOTIVE_PARTS';
export const PURCHASE_CATEGORY_TRANSPORTATION_AUTOMOTIVE_SERVICE = 'PURCHASE_CATEGORY_TRANSPORTATION_AUTOMOTIVE_SERVICE';

// Entertainment
export const PURCHASE_CATEGORY_ENTERTAINMENT_CIGAR_STORES = 'PURCHASE_CATEGORY_ENTERTAINMENT_CIGAR_STORES';
export const PURCHASE_CATEGORY_ENTERTAINMENT_AMUSEMENT_PARKS = 'PURCHASE_CATEGORY_ENTERTAINMENT_AMUSEMENT_PARKS';
export const PURCHASE_CATEGORY_ENTERTAINMENT_MOVIE_THEATER = 'PURCHASE_CATEGORY_ENTERTAINMENT_MOVIE_THEATER';
export const PURCHASE_CATEGORY_ENTERTAINMENT_HOTEL = 'PURCHASE_CATEGORY_ENTERTAINMENT_HOTEL';
export const PURCHASE_CATEGORY_ENTERTAINMENT_BAR_NIGHTCLUB = 'PURCHASE_CATEGORY_ENTERTAINMENT_BAR_NIGHTCLUB';
export const PURCHASE_CATEGORY_ENTERTAINMENT_GAMBLING = 'PURCHASE_CATEGORY_ENTERTAINMENT_GAMBLING';
export const PURCHASE_CATEGORY_ENTERTAINMENT_CRUISE_LINES = 'PURCHASE_CATEGORY_ENTERTAINMENT_CRUISE_LINES';
export const PURCHASE_CATEGORY_ENTERTAINMENT_LIQUOR_STORE = 'PURCHASE_CATEGORY_ENTERTAINMENT_LIQUOR_STORE';
