import {
  ACTIVITY_TYPE_PURCHASE,
  ACTIVITY_TYPE_MEAL,
  ACTIVITY_TYPE_TRANSPORTATION,
  PURCHASE_CATEGORY_FOOD_RESTAURANT,
  PURCHASE_CATEGORY_TRANSPORTATION_TAXI,
  PURCHASE_CATEGORY_TRANSPORTATION_RAILROAD,
  PURCHASE_CATEGORY_TRANSPORTATION_AIRLINES,
  TRANSPORTATION_MODE_PLANE,
  TRANSPORTATION_MODE_TRAIN,
  TRANSPORTATION_MODE_ICE_CAR,
} from '../../definitions';

export function getActivityTypeForCategory(category) {
  switch (category) {
    case PURCHASE_CATEGORY_FOOD_RESTAURANT:
      return ACTIVITY_TYPE_MEAL;
    case PURCHASE_CATEGORY_TRANSPORTATION_TAXI:
    case PURCHASE_CATEGORY_TRANSPORTATION_RAILROAD:
    case PURCHASE_CATEGORY_TRANSPORTATION_AIRLINES:
      return ACTIVITY_TYPE_TRANSPORTATION;
    default:
      return ACTIVITY_TYPE_PURCHASE;
  }
}

export function getTransportationModeForCategory(category) {
  switch (category) {
    case PURCHASE_CATEGORY_TRANSPORTATION_TAXI:
      return TRANSPORTATION_MODE_ICE_CAR;
    case PURCHASE_CATEGORY_TRANSPORTATION_RAILROAD:
      return TRANSPORTATION_MODE_TRAIN;
    case PURCHASE_CATEGORY_TRANSPORTATION_AIRLINES:
      return TRANSPORTATION_MODE_PLANE;
    default:
      return null;
  }
}
